Run commit and push on condition

diff --git a/.github/workflows/update_readme.yml b/.github/workflows/update_readme.yml
--- a/.github/workflows/update_readme.yml
+++ b/.github/workflows/update_readme.yml
@@ -56,13 +56,16 @@ jobs:
       - name: Git status
         run: |
           git status
+          # Get the exit code of the last command and save it to the COMMIT_REQUIRED variable
+          git diff --quiet --exit-code
+          echo "COMMIT_REQUIRED=$(echo $?)" >> $GITHUB_ENV
 
       - name: Push changes to Github
+        if: ${{ env.COMMIT_REQUIRED == 1 }}
         run: |
-          if ! git diff --no-ext-diff --quiet --exit-code; then
-            git config --global user.name "Automatic README update"
-            git config --global user.email "actions@github.com"
-            git add .
-            git commit -m "Update README.md"
-            git push
-          fi
+          git config --global user.name "Automatic README update"
+          git config --global user.email "actions@github.com"
+          git add .
+          git commit -m "Update README.md"
+          git push
+
